trigger: none

pr: none

pool:
  name: 'SanjaySelfHosted'
  demands:
  - agent.name -equals MSBuildWindowsAgent

variables:
  buildConfiguration: 'Release'

jobs:
- job: 'TestAgentWithBash'
  displayName: 'Test Agent - Bash Build'
  steps:
  - checkout: self

  - bash: |
      echo "Testing self-hosted agent..."
      echo "Current directory: $(pwd)"
      echo "Listing files:"
      ls -la
      echo ""
      echo "Building with dotnet CLI..."
      dotnet build --configuration Release
    displayName: 'Build with Bash - dotnet build'

- job: 'TestAgentWithDotNetTask'
  displayName: 'Test Agent - DotNetCoreCLI Task'
  steps:
  - checkout: self

  - task: DotNetCoreCLI@2
    displayName: 'Build with DotNetCoreCLI - All frameworks'
    inputs:
      command: 'build'
      projects: '**/*.sln*'
      arguments: '--configuration $(buildConfiguration)'
