trigger: none

pr: none

pool:
  name: 'SanjaySelfHosted'
  demands:
  - agent.name -equals MSBuildWindowsAgent

variables:
  buildConfiguration: 'Release'

jobs:
- job: 'TestAgentWithPowerShell'
  displayName: 'Test Agent - PowerShell Build'
  steps:
  - checkout: self

  - powershell: |
      Write-Host "Testing self-hosted agent..."
      Write-Host "Current directory: $(Get-Location)"
      Write-Host "Listing files:"
      Get-ChildItem
      Write-Host ""
      Write-Host "Building with dotnet CLI..."
      dotnet build --configuration Release
    displayName: 'Build with PowerShell - dotnet build'

- job: 'TestAgentWithDotNetTask'
  displayName: 'Test Agent - DotNetCoreCLI Task'
  steps:
  - checkout: self

  - task: DotNetCoreCLI@2
    displayName: 'Build with DotNetCoreCLI - All frameworks'
    inputs:
      command: 'build'
      projects: '**/*.sln*'
      arguments: '--configuration $(buildConfiguration)'
