trigger: none

pr: none

pool:
  name: 'SanjaySelfHosted'
  demands:
  - agent.name -equals MSBuildWindowsAgent

variables:
  buildConfiguration: 'Release'

jobs:
- job: 'TestMSBuild'
  displayName: 'Test MSBuild Task'
  steps:
  - checkout: self

  - task: MSBuild@1
    displayName: 'Build with MSBuild'
    inputs:
      solution: '**/*.sln*'
      msbuildArchitecture: 'x64'
      msbuildLocationMethod: 'version'
      msbuildVersion: 'latest'
      platform: 'Any CPU'
      configuration: '$(buildConfiguration)'
      maximumCpuCount: true
