# Azure Pipeline - DotNetCoreCLI Package Source Mapping Bug Reproduction
# Testing the feed- prefix issue with packageSourceMapping

trigger: none
pr: none

variables:
  buildConfiguration: 'Release'

jobs:
# ==============================================================================
# Ubuntu 24.04 Test
# ==============================================================================
- job: Ubuntu_2404
  displayName: 'Ubuntu 24.04 - DotNetCoreCLI Restore'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'ubuntu-24.04'
  steps:
  - checkout: self
    clean: true

  - task: DotNetCoreCLI@2
    displayName: 'Restore with nuget.config'
    inputs:
      command: 'restore'
      projects: '**/*.sln'
      selectOrConfig: 'config'
      nugetConfigPath: 'nuget.config'
      verbosityRestore: 'Detailed'
      noCache: true

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '**/*.sln'
      arguments: '--configuration $(buildConfiguration) --no-restore'
